### ISSUE TITLE
Crashing in .NET 7

### ISSUE THREAD

**Issue by rushfrisby** [costinbanu/CryptSharp.Core#1]
In .NET 6 and in previous versions of .NET this works fine but when I upgraded to .NET 7 it broke. I get an "Access Violation" exception and my app crashes. I don't seem to be able to catch an exception for handling it either.

```csharp
private const int DerivedKeyLength = 64;
private const int Parallel = 16;
private const int BlockSize = 8;
private const int Cost = 1024;
private const string UserSaltKey = "private";

public void SaltAndHashPassword(User user, string password)
{
    var salt = Encoding.UTF8.GetBytes(GetSalt());
    var hashedPassword = SCrypt.ComputeDerivedKey(Encoding.UTF8.GetBytes(password), salt, Cost, BlockSize, Parallel, null, DerivedKeyLength);
    user.Password = Convert.ToBase64String(hashedPassword);
    user.Salt = Convert.ToBase64String(AES.Encrypt(salt, UserSaltKey));
}
```

It's crashing when calling `SCrypt.ComputeDerivedKey()`

The message I get in my output window is

`The program '[26616] Auth.WebServices.exe' has exited with code 3221225477 (0xc0000005) 'Access violation'.`

Is this something with the library that needs to be changed or is this an issue with .NET 7?

**Comment by costinbanu** [comment]
This library has never been tested in .NET 7, therefore I wouldn't know if it is a library problem or a framework problem..NET 7 support has not been planned for yet. I will definitely look into it at some point, but I can't provide an ETA right now.In the meantime, feel free to investigate yourself and create a PR if you find a fix. That I can have a look at quicker.If you are in a hurry and just can't wait for me, then feel free to fork it. I would appreciate, though, a notification on whether you found the issue so that I can look into your fix and pick it up here.Thanks, Costin
-------- Original message --------From: Rush ***@***.***> Date: 11/16/22  04:06  (GMT+01:00) To: "costinbanu/CryptSharp.Core" ***@***.***> Cc: Subscribed ***@***.***> Subject: [costinbanu/CryptSharp.Core] Crashing in .NET 7 (Issue #1) 
In .NET 6 and in previous versions of .NET this works fine but when I upgraded to .NET 7 it broke. I get an "Access Violation" exception and my app crashes. I don't seem to be able to catch an exception for handling it either.
private const int DerivedKeyLength = 64;
private const int Parallel = 16;
private const int BlockSize = 8;
private const int Cost = 1024;
private const string UserSaltKey = "private";

public void SaltAndHashPassword(User user, string password)
{
    var salt = Encoding.UTF8.GetBytes(GetSalt());
    var hashedPassword = SCrypt.ComputeDerivedKey(Encoding.UTF8.GetBytes(password), salt, Cost, BlockSize, Parallel, null, DerivedKeyLength);
    user.Password = Convert.ToBase64String(hashedPassword);
    user.Salt = Convert.ToBase64String(AES.Encrypt(salt, UserSaltKey));
}
It's crashing when calling SCrypt.ComputeDerivedKey()
The message I get in my output window is
The program '[26616] Auth.WebServices.exe' has exited with code 3221225477 (0xc0000005) 'Access violation'.
Is this something with the library that needs to be changed or is this an issue with .NET 7?

**Comment by rushfrisby** [comment]
Done - https://github.com/costinbanu/CryptSharp.Core/pull/2
